DigitSuo Neural Network Digit Recognition: src/draw_interface.c File Reference
draw_interface.c File Reference
#include <stdlib.h>
#include <ncurses.h>
#include <stdio.h>
#include "draw_interface.h"
Functions
static int is_valid_position (int x, int y)
static void reset_cells (DrawGrid *grid)
DrawGrid * init_grid (void)
void free_grid (DrawGrid *grid)
static void clear_interface_lines (void)
static void draw_cells (const DrawGrid *grid)
void draw_interface (DrawGrid *grid)
static void draw_point_with_neighbors (DrawGrid *grid, int x, int y)
static void draw_line (DrawGrid *grid, int x0, int y0, int x1, int y1)
void handle_mouse_event (DrawGrid *grid, int x, int y)
void move_cursor (DrawGrid *grid, int direction)
void toggle_cell (DrawGrid *grid)
void clear_grid (DrawGrid *grid)
Variables
FILE * debug_log
Function Documentation
clear_grid()
void clear_grid (DrawGrid * grid)
Definition at line 171 of file draw_interface.c.
{
    reset_cells(grid);
}
References reset_cells().
Referenced by draw_digit_pattern(), and process_input().
clear_interface_lines()
static void clear_interface_lines (void) static
Definition at line 40 of file draw_interface.c.
{
    for (int i = 0; i < GRID_SIZE; i++)
    {
        move(i, 0);
        clrtoeol();
    }
}
References GRID_SIZE.
Referenced by draw_interface().
draw_cells()
static void draw_cells (const DrawGrid * grid) static
Definition at line 49 of file draw_interface.c.
{
    for (int i = 0; i < GRID_SIZE; i++)
    {
        for (int j = 0; j < GRID_SIZE; j++)
        {
            int screen_y = i;
            int screen_x = j * CELL_WIDTH;
            if (grid->cells[i][j])
            {
                attron(A_BOLD);
                mvaddstr(screen_y, screen_x, "##");
                attroff(A_BOLD);
            }
            else
            {
                mvaddstr(screen_y, screen_x, ". ");
            }
        }
    }
}
References CELL_WIDTH, DrawGrid::cells, and GRID_SIZE.
Referenced by draw_interface().
draw_interface()
void draw_interface (DrawGrid * grid)
Definition at line 71 of file draw_interface.c.
{
    clear_interface_lines();
    draw_cells(grid);
}
References clear_interface_lines(), and draw_cells().
Referenced by main().
draw_line()
static void draw_line (DrawGrid * grid, int x0, int y0, int x1, int y1) static
Definition at line 91 of file draw_interface.c.
{
    int dx = abs(x1 - x0);
    int dy = abs(y1 - y0);
    int sx = (x0 < x1) ? 1 : -1;
    int sy = (y0 < y1) ? 1 : -1;
    int err = (dx > dy ? dx : -dy) / 2;
    int e2;
    while (1)
    {
        draw_point_with_neighbors(grid, x0, y0);
        if (x0 == x1 && y0 == y1)
            break;
        e2 = err;
        if (e2 > -dx)
        {
            err -= dy;
            x0 += sx;
        }
        if (e2 < dy)
        {
            err += dx;
            y0 += sy;
        }
    }
}
References draw_point_with_neighbors().
Referenced by handle_mouse_event().
draw_point_with_neighbors()
static void draw_point_with_neighbors (DrawGrid * grid, int x, int y) static
Definition at line 77 of file draw_interface.c.
{
    if (is_valid_position(x, y))
        grid->cells[y][x] = 1;
    if (is_valid_position(x + 1, y))
        grid->cells[y][x + 1] = 1;
    if (is_valid_position(x - 1, y))
        grid->cells[y][x - 1] = 1;
    if (is_valid_position(x, y + 1))
        grid->cells[y + 1][x] = 1;
    if (is_valid_position(x, y - 1))
        grid->cells[y - 1][x] = 1;
}
References DrawGrid::cells, and is_valid_position().
Referenced by draw_line().
free_grid()
void free_grid (DrawGrid * grid)
Definition at line 35 of file draw_interface.c.
{
    free(grid);
}
Referenced by init_systems(), and main().
handle_mouse_event()
void handle_mouse_event (DrawGrid * grid, int x, int y)
Definition at line 118 of file draw_interface.c.
{
    int grid_x = x / CELL_WIDTH;
    int grid_y = y;
    if (!is_valid_position(grid_x, grid_y))
    {
        if (debug_log)
        {
            fprintf(debug_log, "Mouse event out of bounds: (%d,%d) -> grid(%d,%d)\n", x, y, grid_x, grid_y);
            fflush(debug_log);
        }
        return;
    }
    if (debug_log)
    {
        fprintf(debug_log, "Drawing at grid position: (%d,%d)\n", grid_x, grid_y);
        fflush(debug_log);
    }
    int prev_x = grid->cursor_x;
    int prev_y = grid->cursor_y;
    grid->cursor_x = grid_x;
    grid->cursor_y = grid_y;
    draw_line(grid, prev_x, prev_y, grid_x, grid_y);
}
References CELL_WIDTH, DrawGrid::cursor_x, DrawGrid::cursor_y, debug_log, draw_line(), and is_valid_position().
Referenced by process_mouse_event().
init_grid()
DrawGrid * init_grid (void)
Definition at line 24 of file draw_interface.c.
{
    DrawGrid *grid = malloc(sizeof(DrawGrid));
    if (!grid)
        return NULL;
    reset_cells(grid);
    grid->cursor_x = GRID_SIZE / 2;
    grid->cursor_y = GRID_SIZE / 2;
    return grid;
}
References DrawGrid::cursor_x, DrawGrid::cursor_y, GRID_SIZE, and reset_cells().
Referenced by init_systems().
is_valid_position()
static int is_valid_position (int x, int y) static
Definition at line 8 of file draw_interface.c.
{
    return (x >= 0 && x < GRID_SIZE && y >= 0 && y < GRID_SIZE);
}
References GRID_SIZE.
Referenced by draw_point_with_neighbors(), and handle_mouse_event().
move_cursor()
void move_cursor (DrawGrid * grid, int direction)
Definition at line 143 of file draw_interface.c.
{
    switch (direction)
    {
    case KEY_UP:
        if (grid->cursor_y > 0)
            grid->cursor_y--;
        break;
    case KEY_DOWN:
        if (grid->cursor_y < GRID_SIZE - 1)
            grid->cursor_y++;
        break;
    case KEY_LEFT:
        if (grid->cursor_x > 0)
            grid->cursor_x--;
        break;
    case KEY_RIGHT:
        if (grid->cursor_x < GRID_SIZE - 1)
            grid->cursor_x++;
        break;
    }
}
References DrawGrid::cursor_x, DrawGrid::cursor_y, and GRID_SIZE.
reset_cells()
static void reset_cells (DrawGrid * grid) static
Definition at line 13 of file draw_interface.c.
{
    for (int i = 0; i < GRID_SIZE; i++)
    {
        for (int j = 0; j < GRID_SIZE; j++)
        {
            grid->cells[i][j] = 0;
        }
    }
}
References DrawGrid::cells, and GRID_SIZE.
Referenced by clear_grid(), and init_grid().
toggle_cell()
void toggle_cell (DrawGrid * grid)
Definition at line 166 of file draw_interface.c.
{
    grid->cells[grid->cursor_y][grid->cursor_x] = !grid->cells[grid->cursor_y][grid->cursor_x];
}
References DrawGrid::cells, DrawGrid::cursor_x, and DrawGrid::cursor_y.
Variable Documentation
debug_log
FILE* debug_log extern
Definition at line 46 of file main.c.
Referenced by close_debug_log(), debug_print_grid(), forward_pass(), handle_mouse_event(), init_neural_net(), main(), open_debug_log(), preprocess_grid(), and process_mouse_event().