DigitSuo Neural Network Digit Recognition: src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>
#include "draw_interface.h"
#include "neural_net.h"
#include "utils.h"
Macros
#define MIN_TERM_HEIGHT 10
#define MIN_TERM_WIDTH 40
#define MOUSE_TRACKING_ON "\033[?1002h"
#define MOUSE_ALL_EVENTS_ON "\033[?1003h"
#define MOUSE_EXTENDED_SGR_ON "\033[?1006h"
#define MOUSE_URXVT_ON "\033[?1015h"
#define MOUSE_BASIC_ON "\033[?1000h"
#define MOUSE_BASIC_OFF "\033[?1000l"
#define MOUSE_TRACKING_OFF "\033[?1002l"
#define MOUSE_ALL_EVENTS_OFF "\033[?1003l"
#define MOUSE_EXTENDED_SGR_OFF "\033[?1006l"
#define MOUSE_URXVT_OFF "\033[?1015l"
Functions
static void update_cell (DrawGrid *grid, int x, int y, char c)
static void process_pattern_character (DrawGrid *grid, char c, int *x, int *y)
static void draw_digit_pattern (DrawGrid *grid, int digit)
static FILE * init_debug_log (void)
static void init_ncurses_mode (void)
static int verify_terminal_size (FILE *log)
static int init_systems (DrawGrid **grid, NeuralNet **net)
static void enable_mouse_support (void)
static void disable_mouse_support (void)
static void print_controls (void)
static void process_digit_input (DrawGrid *grid, int ch)
static void process_mouse_event (DrawGrid *grid, MEVENT *last_event)
static void process_submission (DrawGrid *grid, NeuralNet *net)
static int process_input (DrawGrid *grid, NeuralNet *net, MEVENT *last_event)
int main (void)
Variables
FILE * debug_log = NULL
static const char * test_patterns []
Macro Definition Documentation
MIN_TERM_HEIGHT
#define MIN_TERM_HEIGHT 10
Definition at line 31 of file main.c.
MIN_TERM_WIDTH
#define MIN_TERM_WIDTH 40
Definition at line 32 of file main.c.
MOUSE_ALL_EVENTS_OFF
#define MOUSE_ALL_EVENTS_OFF "\033[?1003l"
Definition at line 42 of file main.c.
MOUSE_ALL_EVENTS_ON
#define MOUSE_ALL_EVENTS_ON "\033[?1003h"
Definition at line 35 of file main.c.
MOUSE_BASIC_OFF
#define MOUSE_BASIC_OFF "\033[?1000l"
Definition at line 40 of file main.c.
MOUSE_BASIC_ON
#define MOUSE_BASIC_ON "\033[?1000h"
Definition at line 38 of file main.c.
MOUSE_EXTENDED_SGR_OFF
#define MOUSE_EXTENDED_SGR_OFF "\033[?1006l"
Definition at line 43 of file main.c.
MOUSE_EXTENDED_SGR_ON
#define MOUSE_EXTENDED_SGR_ON "\033[?1006h"
Definition at line 36 of file main.c.
MOUSE_TRACKING_OFF
#define MOUSE_TRACKING_OFF "\033[?1002l"
Definition at line 41 of file main.c.
MOUSE_TRACKING_ON
#define MOUSE_TRACKING_ON "\033[?1002h"
Definition at line 34 of file main.c.
MOUSE_URXVT_OFF
#define MOUSE_URXVT_OFF "\033[?1015l"
Definition at line 44 of file main.c.
MOUSE_URXVT_ON
#define MOUSE_URXVT_ON "\033[?1015h"
Definition at line 37 of file main.c.
Function Documentation
disable_mouse_support()
static void disable_mouse_support (void) static
Definition at line 420 of file main.c.
{
    printf(MOUSE_BASIC_OFF);
    printf(MOUSE_TRACKING_OFF);
    printf(MOUSE_ALL_EVENTS_OFF);
    printf(MOUSE_EXTENDED_SGR_OFF);
    printf(MOUSE_URXVT_OFF);
}
References MOUSE_ALL_EVENTS_OFF, MOUSE_BASIC_OFF, MOUSE_EXTENDED_SGR_OFF, MOUSE_TRACKING_OFF, and MOUSE_URXVT_OFF.
Referenced by main().
draw_digit_pattern()
static void draw_digit_pattern (DrawGrid * grid, int digit) static
Definition at line 346 of file main.c.
{
    if (digit < 0 || digit > 9)
        return;
    clear_grid(grid);
    const char *pattern = test_patterns[digit];
    int x = 0, y = 0;
    for (const char *p = pattern; *p != '\0'; p++)
        process_pattern_character(grid, *p, &x, &y);
}
References clear_grid(), process_pattern_character(), and test_patterns.
Referenced by process_digit_input().
enable_mouse_support()
static void enable_mouse_support (void) static
Definition at line 407 of file main.c.
{
    printf(MOUSE_TRACKING_ON);
    printf(MOUSE_ALL_EVENTS_ON);
    printf(MOUSE_EXTENDED_SGR_ON);
    printf(MOUSE_URXVT_ON);
    printf(MOUSE_BASIC_ON);
    mousemask(ALL_MOUSE_EVENTS | REPORT_MOUSE_POSITION, NULL);
    mouseinterval(0);
    curs_set(0);
    timeout(0);
}
References MOUSE_ALL_EVENTS_ON, MOUSE_BASIC_ON, MOUSE_EXTENDED_SGR_ON, MOUSE_TRACKING_ON, and MOUSE_URXVT_ON.
Referenced by main().
init_debug_log()
static FILE * init_debug_log (void) static
Definition at line 357 of file main.c.
{
    FILE *log = fopen(DEBUG_LOG_PATH, "w");
    if (!log)
        fprintf(stderr, "Failed to open debug log\n");
    return log;
}
References DEBUG_LOG_PATH.
Referenced by main().
init_ncurses_mode()
static void init_ncurses_mode (void) static
Definition at line 365 of file main.c.
{
    initscr();
    noecho();
    cbreak();
    keypad(stdscr, TRUE);
}
Referenced by main().
init_systems()
static int init_systems (DrawGrid ** grid, NeuralNet ** net) static
Definition at line 393 of file main.c.
{
    *grid = init_grid();
    if (!*grid)
        return 0;
    *net = init_neural_net();
    if (!*net)
    {
        free_grid(*grid);
        return 0;
    }
    return 1;
}
References free_grid(), init_grid(), and init_neural_net().
Referenced by main().
main()
int main (void)
Definition at line 518 of file main.c.
{
    debug_log = init_debug_log();
    if (!debug_log)
        return 1;
    init_ncurses_mode();
    if (!verify_terminal_size(debug_log))
        return 1;
    DrawGrid *grid = NULL;
    NeuralNet *net = NULL;
    if (!init_systems(&grid, &net))
    {
        endwin();
        fprintf(stderr, "Failed to initialize systems\n");
        fclose(debug_log);
        return 1;
    }
    enable_mouse_support();
    MEVENT last_event = {0};
    int running = 1;
    while (running)
    {
        draw_interface(grid);
        print_controls();
        refresh();
        running = process_input(grid, net, &last_event);
    }
    disable_mouse_support();
    free_neural_net(net);
    free_grid(grid);
    fclose(debug_log);
    endwin();
    return 0;
}
References debug_log, disable_mouse_support(), draw_interface(), enable_mouse_support(), free_grid(), free_neural_net(), init_debug_log(), init_ncurses_mode(), init_systems(), print_controls(), process_input(), and verify_terminal_size().
print_controls()
static void print_controls (void) static
Definition at line 429 of file main.c.
{
    int info_x = (GRID_SIZE * 2) + 2;
    mvprintw(1, info_x, "Controls: 0-9: Digits");
    mvprintw(2, info_x, "Mouse/Arrow: Draw");
    mvprintw(3, info_x, "Enter: Submit  C: Clear");
    mvprintw(4, info_x, "Q: Quit");
}
References GRID_SIZE.
Referenced by main().
process_digit_input()
static void process_digit_input (DrawGrid * grid, int ch) static
Definition at line 438 of file main.c.
{
    draw_digit_pattern(grid, ch - '0');
}
References draw_digit_pattern().
Referenced by process_input().
process_input()
static int process_input (DrawGrid * grid, NeuralNet * net, MEVENT * last_event) static
Definition at line 489 of file main.c.
{
    int ch = getch();
    if (ch >= '0' && ch <= '9')
    {
        process_digit_input(grid, ch);
        return 1;
    }
    if (ch == KEY_MOUSE)
    {
        process_mouse_event(grid, last_event);
        return 1;
    }
    switch (ch)
    {
    case 'c':
    case 'C':
        clear_grid(grid);
        break;
    case '\n':
        process_submission(grid, net);
        break;
    case 'q':
    case 'Q':
        return 0;
    }
    return 1;
}
References clear_grid(), process_digit_input(), process_mouse_event(), and process_submission().
Referenced by main().
process_mouse_event()
static void process_mouse_event (DrawGrid * grid, MEVENT * last_event) static
Definition at line 443 of file main.c.
{
    MEVENT event;
    if (getmouse(&event) == OK)
    {
        fprintf(debug_log, "Mouse event: x=%d, y=%d, bstate=0x%08lx\n", event.x, event.y, (unsigned long)event.bstate);
        fflush(debug_log);
        if (event.x != last_event->x || event.y != last_event->y)
        {
            handle_mouse_event(grid, event.x, event.y);
            *last_event = event;
        }
    }
}
References debug_log, and handle_mouse_event().
Referenced by process_input().
process_pattern_character()
static void process_pattern_character (DrawGrid * grid, char c, int * x, int * y) static
Definition at line 332 of file main.c.
{
    if (c == '\n')
    {
        *x = 0;
        (*y)++;
    }
    else
    {
        update_cell(grid, *x, *y, c);
        (*x)++;
    }
}
References update_cell().
Referenced by draw_digit_pattern().
process_submission()
static void process_submission (DrawGrid * grid, NeuralNet * net) static
Definition at line 458 of file main.c.
{
    float *input = preprocess_grid(grid);
    if (!input)
        return;
    float *output = forward_pass(net, input);
    free(input);
    if (!output)
        return;
    int prediction = get_prediction(output);
    mvprintw(GRID_SIZE + 1, 2, "Predicted: %d (Confidence: %.0f%%)    ", prediction, output[prediction] * 100.0f);
    mvprintw(GRID_SIZE + 2, 2, "Top 3: ");
    int top[3] = {0, 1, 2};
    for (int i = 3; i < 10; i++)
    {
        for (int j = 0; j < 3; j++)
        {
            if (output[i] > output[top[j]])
            {
                for (int k = 2; k > j; k--)
                    top[k] = top[k - 1];
                top[j] = i;
                break;
            }
        }
    }
    for (int i = 0; i < 3; i++)
        mvprintw(GRID_SIZE + 2, 12 + i * 15, "%d (%.0f%%)", top[i], output[top[i]] * 100.0f);
    free(output);
}
References forward_pass(), get_prediction(), GRID_SIZE, and preprocess_grid().
Referenced by process_input().
update_cell()
static void update_cell (DrawGrid * grid, int x, int y, char c) static
Definition at line 326 of file main.c.
{
    if (y < GRID_SIZE && x < GRID_SIZE)
        grid->cells[y][x] = (c == '#') ? 1 : 0;
}
References DrawGrid::cells, and GRID_SIZE.
Referenced by process_pattern_character().
verify_terminal_size()
static int verify_terminal_size (FILE * log) static
Definition at line 373 of file main.c.
{
    int term_height, term_width;
    getmaxyx(stdscr, term_height, term_width);
    if (term_height < MIN_TERM_HEIGHT || term_width < MIN_TERM_WIDTH)
    {
        endwin();
        fprintf(stderr, "\033[2J\033[H");
        fprintf(stderr, "Terminal window too small!\n\n");
        fprintf(stderr, "Current terminal size: %dx%d\n", term_width, term_height);
        fprintf(stderr, "Required size: %dx%d\n\n", MIN_TERM_WIDTH, MIN_TERM_HEIGHT);
        fprintf(stderr, "Please resize your terminal and run again.\n");
        fprintf(stderr, "Tip: The Shell tab in Replit should be expanded.\n\n");
        if (log)
            fclose(log);
        return 0;
    }
    return 1;
}
References MIN_TERM_HEIGHT, and MIN_TERM_WIDTH.
Referenced by main().
Variable Documentation
debug_log
FILE* debug_log = NULL
Definition at line 46 of file main.c.
Referenced by close_debug_log(), debug_print_grid(), forward_pass(), handle_mouse_event(), init_neural_net(), main(), open_debug_log(), preprocess_grid(), and process_mouse_event().
test_patterns
const char* test_patterns[] static
Definition at line 48 of file main.c.
                                     {"............................\n"
                                      "............................\n"
                                      "..........########..........\n"
                                      ".........##########.........\n"
                                      "........###......###........\n"
                                      ".......###........###.......\n"
                                      ".......###........###.......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      "......###..........###......\n"
                                      ".......###........###.......\n"
                                      ".......###........###.......\n"
                                      "........###......###........\n"
                                      ".........##########.........\n"
                                      "..........########..........\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "............####............\n"
                                      "...........#####............\n"
                                      "..........######............\n"
                                      ".........#######............\n"
                                      "........########............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      "............###.............\n"
                                      ".........########...........\n"
                                      ".........########...........\n"
                                      ".........########...........\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      ".........##########.........\n"
                                      "........############........\n"
                                      ".......###........###.......\n"
                                      "..................###.......\n"
                                      "..................###.......\n"
                                      ".................###........\n"
                                      "................###.........\n"
                                      "...............###..........\n"
                                      "..............###...........\n"
                                      ".............###............\n"
                                      "............###.............\n"
                                      "...........###..............\n"
                                      "..........###...............\n"
                                      ".........###................\n"
                                      "........###.................\n"
                                      ".......###..................\n"
                                      "......###...................\n"
                                      ".....###....................\n"
                                      "....###################.....\n"
                                      "....###################.....\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "..........########..........\n"
                                      "........############........\n"
                                      ".......###........###.......\n"
                                      "......###..........###......\n"
                                      "..................###.......\n"
                                      ".................###........\n"
                                      "...........#######..........\n"
                                      "...........#######..........\n"
                                      ".................###........\n"
                                      "..................###.......\n"
                                      "..................###.......\n"
                                      "..................###.......\n"
                                      "..................###.......\n"
                                      "......###.........###......\n"
                                      ".......###........###......\n"
                                      "........###......###.......\n"
                                      ".........##########.........\n"
                                      "...........######...........\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "................###.........\n"
                                      "...............####.........\n"
                                      "..............#####.........\n"
                                      ".............######.........\n"
                                      "............###.###.........\n"
                                      "...........###..###.........\n"
                                      "..........###...###.........\n"
                                      ".........###....###.........\n"
                                      "........###.....###.........\n"
                                      ".......###......###.........\n"
                                      "......###.......###.........\n"
                                      ".....###........###.........\n"
                                      "....###.........###.........\n"
                                      "...##################........\n"
                                      "...##################........\n"
                                      "...##################........\n"
                                      "................###.........\n"
                                      "................###.........\n"
                                      "................###.........\n"
                                      "................###.........\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      ".......############.........\n"
                                      ".......############.........\n"
                                      ".......###..................\n"
                                      ".......###..................\n"
                                      ".......###..................\n"
                                      ".......###..................\n"
                                      ".......###############......\n"
                                      ".......###############......\n"
                                      "..................###.......\n"
                                      "...................###......\n"
                                      "...................###......\n"
                                      "...................###......\n"
                                      "...................###......\n"
                                      "...................###......\n"
                                      "......###.........###......\n"
                                      ".......###.......###.......\n"
                                      "........###.....###........\n"
                                      ".........#########.........\n"
                                      "...........#####...........\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "...........######...........\n"
                                      ".........########..........\n"
                                      "........###................\n"
                                      ".......###..................\n"
                                      "......###...................\n"
                                      ".....###....................\n"
                                      ".....###....................\n"
                                      ".....###....................\n"
                                      ".....###.#########.........\n"
                                      ".....#############.........\n"
                                      "....###..........###.......\n"
                                      "....###..........###.......\n"
                                      "....###..........###.......\n"
                                      "....###..........###.......\n"
                                      ".....###........###........\n"
                                      "......###......###.........\n"
                                      ".......##########..........\n"
                                      ".........######............\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "....##################......\n"
                                      "....##################......\n"
                                      "....##################......\n"
                                      "..................###.......\n"
                                      ".................###........\n"
                                      "................###.........\n"
                                      "...............###..........\n"
                                      "..............###...........\n"
                                      ".............###............\n"
                                      "............###.............\n"
                                      "...........###..............\n"
                                      "..........###...............\n"
                                      ".........###................\n"
                                      "........###.................\n"
                                      ".......###..................\n"
                                      "......###...................\n"
                                      ".....###....................\n"
                                      "....###.....................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "..........######............\n"
                                      "........##########..........\n"
                                      ".......###......###.........\n"
                                      "......###........###........\n"
                                      "......###........###........\n"
                                      "......###........###........\n"
                                      ".......###......###.........\n"
                                      "........########............\n"
                                      "........########............\n"
                                      ".......###......###.........\n"
                                      "......###........###........\n"
                                      "......###........###........\n"
                                      "......###........###........\n"
                                      "......###........###........\n"
                                      ".......###......###.........\n"
                                      "........##########..........\n"
                                      "..........######............\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................",
                                      "............................\n"
                                      "............................\n"
                                      "..........######............\n"
                                      "........##########..........\n"
                                      ".......###......###.........\n"
                                      "......###........###........\n"
                                      ".....###..........###.......\n"
                                      ".....###..........###.......\n"
                                      ".....###..........###.......\n"
                                      ".....###..........###.......\n"
                                      "......###........###........\n"
                                      ".......############.........\n"
                                      ".........##########.........\n"
                                      "...............###..........\n"
                                      "................###.........\n"
                                      "................###.........\n"
                                      ".......###......###.........\n"
                                      "........###....###..........\n"
                                      ".........########...........\n"
                                      "...........####.............\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................\n"
                                      "............................"};
Referenced by draw_digit_pattern().