DigitSuo Neural Network Digit Recognition: src/utils.h File Reference
utils.h File Reference
#include "draw_interface.h"
Macros
#define PREPROCESSING_TARGET_SIZE 18.0f
#define CONTRAST_THRESHOLD 0.3f
#define NORMALIZED_MAX_VALUE 255.0f
#define BINARY_THRESHOLD 128.0f
#define DEBUG_FILLED_CHAR '#'
#define DEBUG_EMPTY_CHAR '.'
#define DEBUG_LOG_PATH "debug.log"
#define DEBUG_LOG_MODE "a"
Functions
float * preprocess_grid (DrawGrid *grid)
Macro Definition Documentation
BINARY_THRESHOLD
#define BINARY_THRESHOLD 128.0f
Definition at line 9 of file utils.h.
CONTRAST_THRESHOLD
#define CONTRAST_THRESHOLD 0.3f
Definition at line 7 of file utils.h.
DEBUG_EMPTY_CHAR
#define DEBUG_EMPTY_CHAR '.'
Definition at line 12 of file utils.h.
DEBUG_FILLED_CHAR
#define DEBUG_FILLED_CHAR '#'
Definition at line 11 of file utils.h.
DEBUG_LOG_MODE
#define DEBUG_LOG_MODE "a"
Definition at line 15 of file utils.h.
DEBUG_LOG_PATH
#define DEBUG_LOG_PATH "debug.log"
Definition at line 14 of file utils.h.
NORMALIZED_MAX_VALUE
#define NORMALIZED_MAX_VALUE 255.0f
Definition at line 8 of file utils.h.
PREPROCESSING_TARGET_SIZE
#define PREPROCESSING_TARGET_SIZE 18.0f
Definition at line 6 of file utils.h.
Function Documentation
preprocess_grid()
float * preprocess_grid (DrawGrid * grid)
Definition at line 111 of file utils.c.
{
    FILE *debug_log = open_debug_log();
    if (!debug_log)
    {
        return NULL;
    }
    GridBounds bounds = find_grid_bounds(grid);
    if (bounds.total_points == 0)
    {
        fprintf(debug_log, "No content found in grid\n");
        close_debug_log(debug_log);
        return NULL;
    }
    GridDimensions dims = calculate_dimensions(&bounds);
    fprintf(debug_log, "Content bounds: (%d,%d) to (%d,%d)\n", bounds.min_x, bounds.min_y, bounds.max_x, bounds.max_y);
    fprintf(debug_log, "Dimensions: %dx%d\n", dims.width, dims.height);
    float scale = PREPROCESSING_TARGET_SIZE / fmax(dims.width, dims.height);
    fprintf(debug_log, "Scale factor: %.3f\n", scale);
    float *input = (float *)calloc(GRID_SIZE * GRID_SIZE, sizeof(float));
    if (!input)
    {
        fprintf(debug_log, "Failed to allocate memory for input\n");
        close_debug_log(debug_log);
        return NULL;
    }
    float target_center_x = GRID_SIZE / 2.0f;
    float target_center_y = GRID_SIZE / 2.0f;
    for (int y = 0; y < GRID_SIZE; y++)
    {
        for (int x = 0; x < GRID_SIZE; x++)
        {
            float src_x = ((x - target_center_x) / scale + dims.center_x);
            float src_y = ((y - target_center_y) / scale + dims.center_y);
            float value = bilinear_interpolate(grid, src_x, src_y);
            value = value > CONTRAST_THRESHOLD ? 1.0f : value;
            input[y * GRID_SIZE + x] = value * NORMALIZED_MAX_VALUE;
        }
    }
    debug_print_grid(debug_log, input);
    close_debug_log(debug_log);
    return input;
}
References bilinear_interpolate(), calculate_dimensions(), GridDimensions::center_x, GridDimensions::center_y, close_debug_log(), CONTRAST_THRESHOLD, debug_log, debug_print_grid(), find_grid_bounds(), GRID_SIZE, GridDimensions::height, GridBounds::max_x, GridBounds::max_y, GridBounds::min_x, GridBounds::min_y, NORMALIZED_MAX_VALUE, open_debug_log(), PREPROCESSING_TARGET_SIZE, GridBounds::total_points, and GridDimensions::width.
Referenced by process_submission().